# Generated by Django 5.0.1 on 2026-02-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_core_adrequ_categor_8516f7_idx_core_adrequ_categor_e52f17_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adrequest',
            new_name='core_adrequ_categor_e52f17_idx',
            old_name='core_adrequ_categor_8516f7_idx',
        ),
    ]
