# Generated by Django 5.2.9 on 2026-02-13 21:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_siteconfiguration_use_arabic_reshaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='Generated image for Feed post (1:1 or 4:5). Used for Telegram channel and Instagram Feed.', null=True, upload_to='generated_ads/'),
        ),
        migrations.AddField(
            model_name='adrequest',
            name='generated_story_image',
            field=models.ImageField(blank=True, help_text='Generated image for Instagram Story (9:16). Never mixed with Feed.', null=True, upload_to='generated_stories/'),
        ),
        migrations.AddField(
            model_name='adrequest',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adrequest',
            name='instagram_story_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adrequest',
            name='is_instagram_published',
            field=models.BooleanField(default=False, help_text='True when at least one of Feed or Story was successfully published to Instagram.'),
        ),
        migrations.AlterField(
            model_name='adrequest',
            name='content',
            field=models.TextField(validators=[core.validators.validate_ad_content_length, core.validators.validate_ad_content_persian]),
        ),
    ]
