# Generated by Django 5.2.9 on 2026-02-13 23:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_phone_layer_size_48'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_instagram_queue', models.BooleanField(default=False, help_text='When ON, approved ads are queued for Instagram and published by the scheduler (max 5 per 24h). When OFF, posts go out immediately.', verbose_name='Add post and story on queue')),
                ('last_post_time', models.DateTimeField(blank=True, db_index=True, help_text='When the last successful Instagram post was made by the queue processor (read-only).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Settings',
                'verbose_name_plural': 'Instagram Settings',
            },
        ),
        migrations.AddField(
            model_name='adrequest',
            name='instagram_queue_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='', help_text='Queued: waiting for scheduler. Sent/Failed: set by queue processor.', max_length=16),
        ),
        migrations.AlterField(
            model_name='adtemplate',
            name='coordinates',
            field=models.JSONField(blank=True, default=core.models.default_adtemplate_coordinates, help_text='JSON with keys: category, description, phone. Each contains x, y, size, color, font_path, align; description also has max_width; phone has letter_spacing. Primary source is static/banner_config.json.'),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
