# Generated by Django 5.2.9 on 2026-02-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_instagram_queue_settings_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_webhook_sync',
            field=models.BooleanField(default=False, help_text='When ON, approved ads are sent to External Webhook URL as JSON.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='external_webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive ad payload when an ad is approved (POST JSON). Leave empty to disable.', max_length=512),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='webhook_secret_key',
            field=models.CharField(blank=True, help_text='Secret sent as X-Webhook-Secret header for webhook verification at destination.', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('telegram_channel', 'Telegram Channel'), ('instagram', 'Instagram'), ('instagram_story', 'Instagram Story'), ('api', 'API'), ('webhook', 'External Webhook')], db_index=True, max_length=24),
        ),
    ]
