# Generated by Django 5.2.9 on 2026-02-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_api_webhook_and_latest_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrequest',
            name='instagram_queue_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Queued: waiting for scheduler. Sent/Failed: set by queue processor.', max_length=16, null=True),
        ),
    ]
