# Generated by Django 5.2.9 on 2026-02-14 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_instagram_queue_status_nullable_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('category', models.CharField(choices=[('INSTAGRAM_API', 'Instagram API'), ('TELEGRAM_BOT', 'Telegram Bot'), ('IMAGE_GENERATION', 'Image Generation'), ('WEBHOOK', 'Webhook'), ('SYSTEM_CORE', 'System Core'), ('DATABASE', 'Database')], db_index=True, default='SYSTEM_CORE', max_length=32)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, help_text='HTTP status (e.g. 200, 400, 500) or internal code', null=True)),
                ('message', models.CharField(help_text='Brief summary of the event', max_length=512)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Payload sent to external services or function arguments', null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='API response or Python traceback on crash', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Browser info, IP, fb_trace_id, etc.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ad_request', models.ForeignKey(blank=True, help_text='Link to AdRequest if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='core.adrequest')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'level'], name='core_system_categor_b5249e_idx'), models.Index(fields=['created_at'], name='core_system_created_3ea7c3_idx'), models.Index(fields=['status_code'], name='core_system_status__8c1f84_idx')],
            },
        ),
    ]
