# Generated by Django 5.0.1 on 2026-03-28 17:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_adrequest_telegram_channel_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrequest',
            name='content',
            field=models.TextField(validators=[core.validators.validate_ad_content_length]),
        ),
    ]
